# network
network: "mainnet"

# p2p
p2p-enabled: true
p2p-port: 9001

# validators
validator-keys: "/launchpad:/launchpad"
validators-keystore-locking-enabled: false

# deposit
eth1-endpoint: http://geth:8545

# metrics
metrics-enabled: true
metrics-categories: ["BEACON","LIBP2P","NETWORK","PROCESS"]
metrics-port: 8008
metrics-interface: 0.0.0.0
metrics-host-allowlist: "*"

# database
data-path: "/opt/teku/data"
data-storage-mode: "archive"

# beacon rest api
rest-api-port: 5051
rest-api-host-allowlist: "*"
rest-api-interface: 0.0.0.0
rest-api-docs-enabled: true
rest-api-enabled: true

log-destination: console
