version: "3.7"

x-disabled-service:
  &disabled-service
    image: tianon/true
    restart: "no"
    command: ""
    entrypoint: ""

services:
  geth:
    <<: *disabled-service
  beacon:
    image: eth2spectrum/prysm-beacon-chain-arm64:${PRYSM_ARM64_DOCKER_TAG}
    volumes:
      - ./config/prysm/beacon-no-geth.yaml:/config/beacon.yaml:ro
      - ./data/prsym/beacon:/data
  validator:
    image: eth2spectrum/prysm-validator-arm64:${PRYSM_ARM64_DOCKER_TAG}
  slasher:
    image: eth2spectrum/prysm-slasher-arm64:${PRYSM_ARM64_DOCKER_TAG}
  prometheus:
    <<: *disabled-service
  grafana:
    <<: *disabled-service
